#!/bin/bash

sudo pacman -S --needed - < pkglist.txt
yay -S --needed - < pkglist_aur.txt
chmod -R +x ./.scripts/
cp -R ./.scripts ~/
sed -i "s/salil/$USER/g" ./.config/bspwm/bspwmrc ./.config/sxhkd/sxhkdrc ./.scripts/wallpaper.sh ./.scripts/reload_dunst.sh ./.scripts/spotifyinfo.sh ./.scripts/getemoji


cp -R ./.config ./.scripts ./.cache ~/
cd ~/.config/st
sudo make install
cd ~/arcoricer
sudo pip3 install pywal
sudo pip install spotify-cli-linux
cp -R wallpapers ~/Pictures/
