#!/bin/bash

sudo pacman -S --needed - < pkglist.txt
sudo pacman -Rs picom
#yay -S --needed - < pkglist_aur.txt
yay -S $(cat pkglist_aur.txt | xargs)
chmod -R +x ./.scripts/
sed -i "s/salil/$USER/g" ./.scripts/* ./.config/bspwm/* ./.config/sxhkd/* ./.config/rofi/* ./.config/fish/*
cp -R ./.config ./.scripts ./.cache ./.local ~/
cd ~/.config/st
sudo make install
cd ~/autoricer
sudo pip3 install pywal
sudo pip install spotify-cli-linux
cp -R wallpapers ~/Pictures/
chsh -s /usr/bin/fish
sudo pacman -Syu
