#!/bin/bash

sudo pacman -S --needed - < pkglist.txt
yay -S --needed - < pkglist_aur.txt
chmod -R +x ./.scripts/
sed -i "s/salil/$USER/g" ./.scripts/* ./.config/*
cp -R ./.config ./.scripts ./.cache ~/
cd ~/.config/st
sudo make install
cd ~/autoricer
sudo pip3 install pywal
sudo pip install spotify-cli-linux
cp -R wallpapers ~/Pictures/
chsh -s /usr/bin/fish
