--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/salil/Pictures/wallpapers/autumn.jpg"

-- Special
background="#0B0D2A"
foreground="#f4eac7"
cursor="#f4eac7"

-- Colors
color0="#0B0D2A"
color1="#BD6D35"
color2="#7B8458"
color3="#ED9831"
color4="#AC8D4D"
color5="#EAA64F"
color6="#FBCD63"
color7="#f4eac7"
color8="#aaa38b"
color9="#BD6D35"
color10="#7B8458"
color11="#ED9831"
color12="#AC8D4D"
color13="#EAA64F"
color14="#FBCD63"
color15="#f4eac7"
