# Shell variables
# Generated by 'wal'
wallpaper='/home/salil/Pictures/wallpapers/autumn.jpg'

# Special
background='#0B0D2A'
foreground='#f4eac7'
cursor='#f4eac7'

# Colors
color0='#0B0D2A'
color1='#BD6D35'
color2='#7B8458'
color3='#ED9831'
color4='#AC8D4D'
color5='#EAA64F'
color6='#FBCD63'
color7='#f4eac7'
color8='#aaa38b'
color9='#BD6D35'
color10='#7B8458'
color11='#ED9831'
color12='#AC8D4D'
color13='#EAA64F'
color14='#FBCD63'
color15='#f4eac7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
