#! /bin/sh

#Autostart stuff
wmname LG3D
sxhkd &


bspc monitor -d I II III IV V VI VII VIII IX X

picom --experimental-backends &
#xset r rate 300 50 &
xset r rate 300 80 &
/home/salil/.scripts/wallpaper.sh
/home/salil/.scripts/launchpolybar
cat /dev/null > /tmp/mybar.log
bspc config border_width         2
bspc config window_gap          12
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
bspc rule -a Zathura state=tiled
bspc rule -a St:calc state=floating sticky=on
bspc rule -a St:notes state=floating sticky=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
. "/home/salil/.cache/wal/colors.sh"
/home/salil/.scripts/reload_dunst.sh
#bspc config normal_border_color "#fabd2f"
#bspc config active_border_color "#fabd2f"
bspc config focused_border_color "$color5"
xsetroot -cursor_name left_ptr &
