#!/bin/bash

# Increase/decrease/set blur to default=5
# The display toggles to "no blur" when blur strength is zero
# WARNING: The script looks for "NUMBER;" (for ex: "5;") in picom.conf and changes it.
# If you have any other instance of "NUMBER;", it will change that too


# Usage: blur_control OPTIONS STRENGTH
# OPTIONS: plus/minus/default
# Example: blur_control plus 10


NUM="${2:-2}"
DIR=/home/salil/.config/picom.conf
BLUR=$(grep "strength = " $DIR | cut -d' ' -f5)
BLUR_NUM=$(echo $BLUR | sed 's/;//g')
STAT=$(grep "normal" /home/salil/.config/picom.conf | cut -d' ' -f8)
STAT_VAL=$(echo $STAT | sed 's/;//g')
TOG1="normal = { blur-background = true;"
TOG0="normal = { blur-background = false;"
case "$1" in
	plus) (("$STAT_VAL"=="false")) && sed -i "s/$TOG0/$TOG1/g" $DIR ; sed -i "s/$BLUR/$(($BLUR_NUM+$NUM));/g" $DIR ;;
	minus) ((BLUR_NUM<NUM)) && sed -i "s/$BLUR/0;/g" $DIR && sed -i "s/$TOG1/$TOG0/g" $DIR || sed -i "s/$BLUR/$(($BLUR_NUM-$NUM));/g" $DIR ;;
	default) sed -i "s/$TOG0/$TOG1/g" $DIR ; sed -i "s/$BLUR/5;/g" $DIR ;;
esac
