#!/bin/bash
# Launches an instance of polybar

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
#while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
echo "---" | tee -a /tmp/mybar.log
polybar mybar >>/tmp/mybar.log 2>&1 & disown
# Launch Polybar, using default config location ~/.config/polybar/config
#polybar mybar &

echo "Polybar launched..."
