#!/usr/bin/env bash
#
# Script to set colors generated by 'wal'
# https://github.com/dylanaraps/wal
 # Source generated colors.
. "/home/salil/.cache/wal/colors.sh"

 reload_dunst() {
    pkill dunst
    dunst \
	-frame_width 0 \
        -lb "${color0}" \
        -nb "${color0}" \
        -cb "${color0}" \
        -lf "${color5}" \
        -bf "${color5}" \
        -cf "${color5}" \
        -nf "${color5}" &
}

reload_dunst
